[platformio]
default_envs = node1

[env]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps = sandeepmistry/LoRa@^0.8.0
monitor_filters = time, colorize, send_on_enter

build_flags = 
    -D BROADCAST_ID=255

[env:node1]
build_flags = 
    ${env.build_flags}
    -D NODE_ID=1
upload_port = COM5
monitor_port = COM5

[env:node2]
build_flags = 
    ${env.build_flags}
    -D NODE_ID=2
upload_port = COM7
monitor_port = COM7